language: php
sudo: false

php:
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.3.*
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=4.0.*

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION=''
    - php: 7.2
      env: SYMFONY_VERSION=''

before_script:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer --no-update require symfony/symfony:${SYMFONY_VERSION}; fi;
  - travis_retry composer update

script:
  - vendor/bin/phpunit

branches:
  only:
    - master
