language: php
sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.3.*
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=4.0.*

matrix:
  include:
    - php: 7.0
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
    - php: 7.0
      env: SYMFONY_VERSION=''
    - php: 7.1
      env: SYMFONY_VERSION=''
    - php: 7.2
      env: SYMFONY_VERSION=''
  exclude:
    - php: 7.0
      env: SYMFONY_VERSION=4.0.*

before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer --no-update require symfony/symfony:${SYMFONY_VERSION}; fi;
  - travis_retry composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit
  - git log $(git describe --abbrev=0 --tags)...HEAD --no-merges --pretty=format:"* [%h](http://github.com/${TRAVIS_REPO_SLUG}/commit/%H) %s (%cN)"

branches:
  only:
    - master
